import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import alias from 'esbuild-plugin-alias';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins,
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [
		alias({
			'@': path.resolve(__dirname, 'src'),
		}),
		{
			name: 'text-files',
			setup(build) {
				build.onLoad({ filter: /\.txt$/ }, async (args) => {
					const text = await import('fs').then((fs) => fs.readFileSync(args.path, 'utf8'));
					return {
						contents: text,
						loader: 'text',
					};
				});
			},
		},
	],
	loader: {
		'.hbs': 'text',
		'.json': 'json',
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
