/**
 * AUTO-GENERATED FILE — DO NOT EDIT
 *
 * Generated by scripts/generate-help-references.mjs
 * Source directories: docs/guide, docs/reference
 *
 * To regenerate: npm run generate-refs
 */

import refAgentMode from '../../docs/guide/agent-mode.md';
import refAgentSkills from '../../docs/guide/agent-skills.md';
import refAiWriting from '../../docs/guide/ai-writing.md';
import refCompletions from '../../docs/guide/completions.md';
import refContextSystem from '../../docs/guide/context-system.md';
import refCustomPrompts from '../../docs/guide/custom-prompts.md';
import refDeepResearch from '../../docs/guide/deep-research.md';
import refFaq from '../../docs/guide/faq.md';
import refGettingStarted from '../../docs/guide/getting-started.md';
import refMcpServers from '../../docs/guide/mcp-servers.md';
import refProjects from '../../docs/guide/projects.md';
import refSemanticSearch from '../../docs/guide/semantic-search.md';
import refSummarization from '../../docs/guide/summarization.md';
import refAdvancedSettings from '../../docs/reference/advanced-settings.md';
import refLoopDetection from '../../docs/reference/loop-detection.md';
import refSettings from '../../docs/reference/settings.md';

export const helpResources = new Map<string, string>([
	['references/agent-mode.md', refAgentMode],
	['references/agent-skills.md', refAgentSkills],
	['references/ai-writing.md', refAiWriting],
	['references/completions.md', refCompletions],
	['references/context-system.md', refContextSystem],
	['references/custom-prompts.md', refCustomPrompts],
	['references/deep-research.md', refDeepResearch],
	['references/faq.md', refFaq],
	['references/getting-started.md', refGettingStarted],
	['references/mcp-servers.md', refMcpServers],
	['references/projects.md', refProjects],
	['references/semantic-search.md', refSemanticSearch],
	['references/summarization.md', refSummarization],
	['references/advanced-settings.md', refAdvancedSettings],
	['references/loop-detection.md', refLoopDetection],
	['references/settings.md', refSettings],
]);

export const helpReferencesTable = `| Reference | Topic |
| --------- | ----- |
| \`references/agent-mode.md\` | Agent Mode Guide |
| \`references/agent-skills.md\` | Agent Skills |
| \`references/ai-writing.md\` | Selection-Based AI Features Guide |
| \`references/completions.md\` | IDE-Style Completions Guide |
| \`references/context-system.md\` | Context System Guide |
| \`references/custom-prompts.md\` | Custom Prompts Guide |
| \`references/deep-research.md\` | Deep Research |
| \`references/faq.md\` | Frequently Asked Questions |
| \`references/getting-started.md\` | Getting Started |
| \`references/mcp-servers.md\` | MCP Servers |
| \`references/projects.md\` | Projects |
| \`references/semantic-search.md\` | Semantic Vault Search |
| \`references/summarization.md\` | Document Summarization Guide |
| \`references/advanced-settings.md\` | Advanced Settings Guide |
| \`references/loop-detection.md\` | Tool Loop Detection |
| \`references/settings.md\` | Settings Reference |`;
